#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_get emoncms/user
user=$RET
if [ -n "$user" ]; then
    user="root"
fi

PASSWD_FILE=/home/$user/.setup/passwd.conf

case "$1" in
    purge)
        if test -f $PASSWD_FILE && grep -Fxq "[MySQL]" $PASSWD_FILE; then
            mysql_root_password=`grep -A3 -P "^\[MySQL\]$" $PASSWD_FILE | grep -m1 "root" | sed "s/root://g" | sed -r "s/\s+//g"`
        fi

        mysql="mysql -uroot"
        if [ ! -z $mysql_root_password ]; then
            mysql="$mysql -p$mysql_root_password"
        fi

        db_get emoncms/mysql_database
        mysql_database_value=$RET

        db_get emoncms/mysql_timeseries
        mysql_timeseries_value=$RET

        db_get emoncms/mysql_user
        mysql_user_value=$RET

        $mysql -e "DROP DATABASE IF EXISTS $mysql_database_value;"
        $mysql -e "DROP DATABASE IF EXISTS $mysql_timeseries_value;"
        $mysql -e "DROP USER IF EXISTS '$mysql_user_value'@'localhost';"
        ;;
    *)
        ;;
esac

#DEBHELPER#

exit 0
