#!/bin/sh
set -e

case "$1" in
    purge)
        # Source debconf library.
        . /usr/share/debconf/confmodule

        db_get emoncms/user
        user=$RET

        passwd_file=/home/$user/.setup/passwd.conf
        if test -f $passwd_file && grep -Fxq "[MySQL]" $passwd_file; then
            mysql_root_password=`grep -A3 -P "^\[MySQL\]$" $passwd_file | grep -m1 "root" | sed "s/root://g" | sed -r "s/\s+//g"`
        fi

        mysql="mysql -uroot"
        if [ ! -z $mysql_root_password ]; then
            mysql="$mysql -p$mysql_root_password"
        fi

        db_get emoncms/mysql_database
        mysql_database_value=$RET

        db_get emoncms/mysql_timeseries
        mysql_timeseries_value=$RET

        db_get emoncms/mysql_user
        mysql_user_value=$RET

        $mysql -e "DROP DATABASE IF EXISTS $mysql_database_value;"
        $mysql -e "DROP DATABASE IF EXISTS $mysql_timeseries_value;"
        $mysql -e "DROP USER IF EXISTS '$mysql_user_value'@'localhost';"
        ;;
    *)
        ;;
esac

#DEBHELPER#

exit 0
