#!/bin/sh
set -e

#DEBHELPER#

case "$1" in
    install | configure)
        if ! grep -q '#CustomLog'             /etc/apache2/conf-available/other-vhosts-access-log.conf; then
            sed -i "s/^CustomLog/#CustomLog/" /etc/apache2/conf-available/other-vhosts-access-log.conf
        fi

        # Enable apache mod rewrite
        a2enmod -q rewrite

        # Default apache2 configuration
        a2enconf -q emoncms.conf

        # Configure virtual host
        if [ -f /etc/apache2/sites-enabled/000-default.conf ]; then
            a2dissite -q 000-default.conf
        fi
        seal_id=$(cat /proc/cpuinfo | grep Serial | cut -d ' ' -f 2 | cut -c9-16)
        seal_domain="$seal_id.seal.isc-konstanz.de"
        if ! grep -q $seal_domain                               /etc/apache2/sites-available/emoncms.conf; then
            sed -i "/ServerName/a\    ServerAlias $seal_domain" /etc/apache2/sites-available/emoncms.conf
        fi
        a2ensite -q emoncms.conf

        systemctl restart apache2
        ;;
    *)
        systemctl reload apache2
        ;;
esac

exit 0
